# Site settings
repository: jtchase08/cookbook
title: Joe and Mak's Recipes
url: "https://www.thechases.me"
baseurl: ""

encoding: utf-8

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Timezone
timezone: 'America/New_York'

# Files to exclude
exclude:
  - .envrc
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - bin
  - images
  - recipes/TEMPLATE.md
  - vendor

include:
  - appetizers-sides
  - breads
  - desserts
  - main-dishes
  - misc
  - soups-salads
  - index.md
  - _pages

# Jekyll Plugins
plugins:
  - jekyll-default-layout
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji

# jekyll-titltes-from-headings config
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false

# Layout

# Sass setup
sass:
  sass_dir: stylesheets
  style: compressed

# Metadata
author:
  name: Joe
  email: jtchase08@gmail.com
  github: jtchase08
  bsky: thechases.me

# Colletctions
collections:
  appetizers-sides:
    output: true
  breads:
    output: true
  desserts:
    output: true
  main-dishes:
    output: true
  misc:
    output: true
  soups-salads:
    output: true

defaults:
  - scope:
      path: appetizers-sides
    values:
      layout: default
      appetizers-sides: true
  - scope:
      path: breads
    values:
      layout: default
      breads: true
  - scope:
      path: desserts
    values:
      layout: default
      desserts: true
  - scope:
      path: main-dishes
    values:
      layout: default
      main-dishes: true
  - scope:
      path: misc
    values:
      layout: default
      misc: true
  - scope:
      path: soups-salads
    values:
      layout: default
      soups-salads: true